[default]
path = "~/Pictures/wallpaper/active/"
sorting = "random" # can not be set to random as group feature does not work

# These two monitors should inherit from [default]
[eDP-1]
group = 1

[DP-4]
group = 1

[DP-3]
group = 1

# This section should treat every other monitor with only the given wallpaper
[any]
path = "~/Pictures/wallpaper/active/dark/wallhaven_cat.png"
